package com.noorconnect.feature.auth

/**
 * Deliberately not the full ISO-3166 list (~195 countries) — this covers the common cases
 * (Arabic/Muslim-majority countries first, then the rest of the widely-used set) and is
 * trivially extensible: add another CountryCode(...) line, nothing else changes. The flag
 * is a plain Unicode emoji (regional indicator sequence) — no image asset needed.
 */
data class CountryCode(
    val nameAr: String,
    val iso: String,
    val dialCode: String,
    val flag: String,
    val nameEn: String = nameAr,
)

val CountryCodes = listOf(
    CountryCode("مصر", "EG", "20", "🇪🇬"),
    CountryCode("السعودية", "SA", "966", "🇸🇦"),
    CountryCode("الإمارات", "AE", "971", "🇦🇪"),
    CountryCode("الكويت", "KW", "965", "🇰🇼"),
    CountryCode("قطر", "QA", "974", "🇶🇦"),
    CountryCode("البحرين", "BH", "973", "🇧🇭"),
    CountryCode("عُمان", "OM", "968", "🇴🇲"),
    CountryCode("الأردن", "JO", "962", "🇯🇴"),
    CountryCode("العراق", "IQ", "964", "🇮🇶"),
    CountryCode("سوريا", "SY", "963", "🇸🇾"),
    CountryCode("لبنان", "LB", "961", "🇱🇧"),
    CountryCode("فلسطين", "PS", "970", "🇵🇸"),
    CountryCode("اليمن", "YE", "967", "🇾🇪"),
    CountryCode("ليبيا", "LY", "218", "🇱🇾"),
    CountryCode("تونس", "TN", "216", "🇹🇳"),
    CountryCode("الجزائر", "DZ", "213", "🇩🇿"),
    CountryCode("المغرب", "MA", "212", "🇲🇦"),
    CountryCode("السودان", "SD", "249", "🇸🇩"),
    CountryCode("الصومال", "SO", "252", "🇸🇴"),
    CountryCode("موريتانيا", "MR", "222", "🇲🇷"),
    CountryCode("جيبوتي", "DJ", "253", "🇩🇯"),
    CountryCode("جزر القمر", "KM", "269", "🇰🇲"),
    CountryCode("تركيا", "TR", "90", "🇹🇷"),
    CountryCode("إيران", "IR", "98", "🇮🇷"),
    CountryCode("باكستان", "PK", "92", "🇵🇰"),
    CountryCode("بنغلاديش", "BD", "880", "🇧🇩"),
    CountryCode("ماليزيا", "MY", "60", "🇲🇾"),
    CountryCode("نيجيريا", "NG", "234", "🇳🇬"),
    CountryCode("الولايات المتحدة", "US", "1", "🇺🇸"),
    CountryCode("المملكة المتحدة", "GB", "44", "🇬🇧"),
    CountryCode("ألمانيا", "DE", "49", "🇩🇪"),
    CountryCode("فرنسا", "FR", "33", "🇫🇷"),
    CountryCode("إسبانيا", "ES", "34", "🇪🇸"),
    CountryCode("كندا", "CA", "1", "🇨🇦"),
    CountryCode("الهند", "IN", "91", "🇮🇳"),
    CountryCode("الصين", "CN", "86", "🇨🇳"),
    CountryCode("روسيا", "RU", "7", "🇷🇺"),
    CountryCode("أفغانستان", "AF", "93", "🇦🇫", "Afghanistan"),
    CountryCode("ألبانيا", "AL", "355", "🇦🇱", "Albania"),
    CountryCode("أندورا", "AD", "376", "🇦🇩", "Andorra"),
    CountryCode("أنغولا", "AO", "244", "🇦🇴", "Angola"),
    CountryCode("أنتيغوا وباربودا", "AG", "1268", "🇦🇬", "Antigua and Barbuda"),
    CountryCode("الأرجنتين", "AR", "54", "🇦🇷", "Argentina"),
    CountryCode("أرمينيا", "AM", "374", "🇦🇲", "Armenia"),
    CountryCode("أستراليا", "AU", "61", "🇦🇺", "Australia"),
    CountryCode("النمسا", "AT", "43", "🇦🇹", "Austria"),
    CountryCode("أذربيجان", "AZ", "994", "🇦🇿", "Azerbaijan"),
    CountryCode("أوغندا", "UG", "256", "🇺🇬", "Uganda"),
    CountryCode("أوكرانيا", "UA", "380", "🇺🇦", "Ukraine"),
    CountryCode("أوروغواي", "UY", "598", "🇺🇾", "Uruguay"),
    CountryCode("أوزبكستان", "UZ", "998", "🇺🇿", "Uzbekistan"),
    CountryCode("إثيوبيا", "ET", "251", "🇪🇹", "Ethiopia"),
    CountryCode("إريتريا", "ER", "291", "🇪🇷", "Eritrea"),
    CountryCode("إستونيا", "EE", "372", "🇪🇪", "Estonia"),
    CountryCode("إسواتيني", "SZ", "268", "🇸🇿", "Eswatini"),
    CountryCode("إكوادور", "EC", "593", "🇪🇨", "Ecuador"),
    CountryCode("إندونيسيا", "ID", "62", "🇮🇩", "Indonesia"),
    CountryCode("أيرلندا", "IE", "353", "🇮🇪", "Ireland"),
    CountryCode("آيسلندا", "IS", "354", "🇮🇸", "Iceland"),
    CountryCode("إيطاليا", "IT", "39", "🇮🇹", "Italy"),
    CountryCode("باراغواي", "PY", "595", "🇵🇾", "Paraguay"),
    CountryCode("بابوا غينيا الجديدة", "PG", "675", "🇵🇬", "Papua New Guinea"),
    CountryCode("بالاو", "PW", "680", "🇵🇼", "Palau"),
    CountryCode("بنما", "PA", "507", "🇵🇦", "Panama"),
    CountryCode("بنين", "BJ", "229", "🇧🇯", "Benin"),
    CountryCode("بوتان", "BT", "975", "🇧🇹", "Bhutan"),
    CountryCode("بوتسوانا", "BW", "267", "🇧🇼", "Botswana"),
    CountryCode("بوركينا فاسو", "BF", "226", "🇧🇫", "Burkina Faso"),
    CountryCode("بوروندي", "BI", "257", "🇧🇮", "Burundi"),
    CountryCode("بوليفيا", "BO", "591", "🇧🇴", "Bolivia"),
    CountryCode("بيرو", "PE", "51", "🇵🇪", "Peru"),
    CountryCode("بيلاروسيا", "BY", "375", "🇧🇾", "Belarus"),
    CountryCode("تايوان", "TW", "886", "🇹🇼", "Taiwan"),
    CountryCode("تايلاند", "TH", "66", "🇹🇭", "Thailand"),
    CountryCode("تركمانستان", "TM", "993", "🇹🇲", "Turkmenistan"),
    CountryCode("تشيلي", "CL", "56", "🇨🇱", "Chile"),
    CountryCode("تنزانيا", "TZ", "255", "🇹🇿", "Tanzania"),
    CountryCode("توغو", "TG", "228", "🇹🇬", "Togo"),
    CountryCode("توفالو", "TV", "688", "🇹🇻", "Tuvalu"),
    CountryCode("جامايكا", "JM", "1876", "🇯🇲", "Jamaica"),
    CountryCode("جزر البهاما", "BS", "1242", "🇧🇸", "Bahamas"),
    CountryCode("جزر مارشال", "MH", "692", "🇲🇭", "Marshall Islands"),
    CountryCode("جزر سليمان", "SB", "677", "🇸🇧", "Solomon Islands"),
    CountryCode("جمهورية أفريقيا الوسطى", "CF", "236", "🇨🇫", "Central African Republic"),
    CountryCode("جمهورية الكونغو الديمقراطية", "CD", "243", "🇨🇩", "Democratic Republic of the Congo"),
    CountryCode("جنوب أفريقيا", "ZA", "27", "🇿🇦", "South Africa"),
    CountryCode("جنوب السودان", "SS", "211", "🇸🇸", "South Sudan"),
    CountryCode("جورجيا", "GE", "995", "🇬🇪", "Georgia"),
    CountryCode("الدنمارك", "DK", "45", "🇩🇰", "Denmark"),
    CountryCode("دومينيكا", "DM", "1767", "🇩🇲", "Dominica"),
    CountryCode("جمهورية الدومينيكان", "DO", "1809", "🇩🇴", "Dominican Republic"),
    CountryCode("زامبيا", "ZM", "260", "🇿🇲", "Zambia"),
    CountryCode("زيمبابوي", "ZW", "263", "🇿🇼", "Zimbabwe"),
    CountryCode("سان مارينو", "SM", "378", "🇸🇲", "San Marino"),
    CountryCode("ساو تومي وبرينسيبي", "ST", "239", "🇸🇹", "Sao Tome and Principe"),
    CountryCode("سريلانكا", "LK", "94", "🇱🇰", "Sri Lanka"),
    CountryCode("سورينام", "SR", "597", "🇸🇷", "Suriname"),
    CountryCode("سيشل", "SC", "248", "🇸🇨", "Seychelles"),
    CountryCode("سيراليون", "SL", "232", "🇸🇱", "Sierra Leone"),
    CountryCode("سلوفاكيا", "SK", "421", "🇸🇰", "Slovakia"),
    CountryCode("سلوفينيا", "SI", "386", "🇸🇮", "Slovenia"),
    CountryCode("سويسرا", "CH", "41", "🇨🇭", "Switzerland"),
    CountryCode("طاجيكستان", "TJ", "992", "🇹🇯", "Tajikistan"),
    CountryCode("غابون", "GA", "241", "🇬🇦", "Gabon"),
    CountryCode("غامبيا", "GM", "220", "🇬🇲", "Gambia"),
    CountryCode("غانا", "GH", "233", "🇬🇭", "Ghana"),
    CountryCode("غرينادا", "GD", "1473", "🇬🇩", "Grenada"),
    CountryCode("غواتيمالا", "GT", "502", "🇬🇹", "Guatemala"),
    CountryCode("غينيا", "GN", "224", "🇬🇳", "Guinea"),
    CountryCode("غينيا بيساو", "GW", "245", "🇬🇼", "Guinea-Bissau"),
    CountryCode("غيانا", "GY", "592", "🇬🇾", "Guyana"),
    CountryCode("فانواتو", "VU", "678", "🇻🇺", "Vanuatu"),
    CountryCode("فنزويلا", "VE", "58", "🇻🇪", "Venezuela"),
    CountryCode("فيتنام", "VN", "84", "🇻🇳", "Vietnam"),
    CountryCode("فيجي", "FJ", "679", "🇫🇯", "Fiji"),
    CountryCode("قبرص", "CY", "357", "🇨🇾", "Cyprus"),
    CountryCode("قيرغيزستان", "KG", "996", "🇰🇬", "Kyrgyzstan"),
    CountryCode("كازاخستان", "KZ", "7", "🇰🇿", "Kazakhstan"),
    CountryCode("كرواتيا", "HR", "385", "🇭🇷", "Croatia"),
    CountryCode("كوستاريكا", "CR", "506", "🇨🇷", "Costa Rica"),
    CountryCode("كوبا", "CU", "53", "🇨🇺", "Cuba"),
    CountryCode("كولومبيا", "CO", "57", "🇨🇴", "Colombia"),
    CountryCode("كيريباتي", "KI", "686", "🇰🇮", "Kiribati"),
    CountryCode("لاوس", "LA", "856", "🇱🇦", "Laos"),
    CountryCode("لاتفيا", "LV", "371", "🇱🇻", "Latvia"),
    CountryCode("ليتوانيا", "LT", "370", "🇱🇹", "Lithuania"),
    CountryCode("ليختنشتاين", "LI", "423", "🇱🇮", "Liechtenstein"),
    CountryCode("لوكسمبورغ", "LU", "352", "🇱🇺", "Luxembourg"),
    CountryCode("مدغشقر", "MG", "261", "🇲🇬", "Madagascar"),
    CountryCode("ملاوي", "MW", "265", "🇲🇼", "Malawi"),
    CountryCode("مالي", "ML", "223", "🇲🇱", "Mali"),
    CountryCode("مالطا", "MT", "356", "🇲🇹", "Malta"),
    CountryCode("مقدونيا الشمالية", "MK", "389", "🇲🇰", "North Macedonia"),
    CountryCode("موناكو", "MC", "377", "🇲🇨", "Monaco"),
    CountryCode("منغوليا", "MN", "976", "🇲🇳", "Mongolia"),
    CountryCode("موزمبيق", "MZ", "258", "🇲🇿", "Mozambique"),
    CountryCode("مولدوفا", "MD", "373", "🇲🇩", "Moldova"),
    CountryCode("ميكرونيسيا", "FM", "691", "🇫🇲", "Micronesia"),
    CountryCode("ناميبيا", "NA", "264", "🇳🇦", "Namibia"),
    CountryCode("ناورو", "NR", "674", "🇳🇷", "Nauru"),
    CountryCode("نيبال", "NP", "977", "🇳🇵", "Nepal"),
    CountryCode("نيكاراغوا", "NI", "505", "🇳🇮", "Nicaragua"),
    CountryCode("نيوزيلندا", "NZ", "64", "🇳🇿", "New Zealand"),
    CountryCode("النرويج", "NO", "47", "🇳🇴", "Norway"),
    CountryCode("هندوراس", "HN", "504", "🇭🇳", "Honduras"),
    CountryCode("هايتي", "HT", "509", "🇭🇹", "Haiti"),
    CountryCode("هولندا", "NL", "31", "🇳🇱", "Netherlands"),
    CountryCode("هنغاريا", "HU", "36", "🇭🇺", "Hungary"),
    CountryCode("اليابان", "JP", "81", "🇯🇵", "Japan"),
        CountryCode("بربادوس", "BB", "1246", "🇧🇧", "Barbados"),
        CountryCode("بلجيكا", "BE", "32", "🇧🇪", "Belgium"),
        CountryCode("بليز", "BZ", "501", "🇧🇿", "Belize"),
        CountryCode("البرازيل", "BR", "55", "🇧🇷", "Brazil"),
        CountryCode("بروناي", "BN", "673", "🇧🇳", "Brunei"),
        CountryCode("بلغاريا", "BG", "359", "🇧🇬", "Bulgaria"),
        CountryCode("الرأس الأخضر", "CV", "238", "🇨🇻", "Cabo Verde"),
        CountryCode("كمبوديا", "KH", "855", "🇰🇭", "Cambodia"),
        CountryCode("الكاميرون", "CM", "237", "🇨🇲", "Cameroon"),
        CountryCode("تشاد", "TD", "235", "🇹🇩", "Chad"),
        CountryCode("جمهورية الكونغو", "CG", "242", "🇨🇬", "Congo"),
        CountryCode("ساحل العاج", "CI", "225", "🇨🇮", "Cote d'Ivoire"),
        CountryCode("التشيك", "CZ", "420", "🇨🇿", "Czechia"),
        CountryCode("السلفادور", "SV", "503", "🇸🇻", "El Salvador"),
        CountryCode("غينيا الاستوائية", "GQ", "240", "🇬🇶", "Equatorial Guinea"),
        CountryCode("فنلندا", "FI", "358", "🇫🇮", "Finland"),
        CountryCode("اليونان", "GR", "30", "🇬🇷", "Greece"),
        CountryCode("إسرائيل", "IL", "972", "🇮🇱", "Israel"),
        CountryCode("كوسوفو", "XK", "383", "🇽🇰", "Kosovo"),
        CountryCode("ليسوتو", "LS", "266", "🇱🇸", "Lesotho"),
        CountryCode("موريشيوس", "MU", "230", "🇲🇺", "Mauritius"),
        CountryCode("المكسيك", "MX", "52", "🇲🇽", "Mexico"),
        CountryCode("الجبل الأسود", "ME", "382", "🇲🇪", "Montenegro"),
        CountryCode("ميانمار", "MM", "95", "🇲🇲", "Myanmar"),
        CountryCode("النيجر", "NE", "227", "🇳🇪", "Niger"),
        CountryCode("كوريا الشمالية", "KP", "850", "🇰🇵", "North Korea"),
        CountryCode("الفلبين", "PH", "63", "🇵🇭", "Philippines"),
        CountryCode("البرتغال", "PT", "351", "🇵🇹", "Portugal"),
        CountryCode("رومانيا", "RO", "40", "🇷🇴", "Romania"),
        CountryCode("رواندا", "RW", "250", "🇷🇼", "Rwanda"),
        CountryCode("سانت كيتس ونيفيس", "KN", "1869", "🇰🇳", "Saint Kitts and Nevis"),
        CountryCode("سانت لوسيا", "LC", "1758", "🇱🇨", "Saint Lucia"),
        CountryCode("سانت فنسنت والغرينادين", "VC", "1784", "🇻🇨", "Saint Vincent and the Grenadines"),
        CountryCode("ساموا", "WS", "685", "🇼🇸", "Samoa"),
        CountryCode("السنغال", "SN", "221", "🇸🇳", "Senegal"),
        CountryCode("سنغافورة", "SG", "65", "🇸🇬", "Singapore"),
        CountryCode("كوريا الجنوبية", "KR", "82", "🇰🇷", "South Korea"),
        CountryCode("السويد", "SE", "46", "🇸🇪", "Sweden"),
        CountryCode("تونغا", "TO", "676", "🇹🇴", "Tonga"),
        CountryCode("ترينيداد وتوباغو", "TT", "1868", "🇹🇹", "Trinidad and Tobago"),
        CountryCode("الفاتيكان", "VA", "39", "🇻🇦", "Vatican City"),
        CountryCode("ليبيريا", "LR", "231", "🇱🇷", "Liberia"),
        CountryCode("جزر المالديف", "MV", "960", "🇲🇻", "Maldives"),
        CountryCode("تيمور الشرقية", "TL", "670", "🇹🇱", "Timor-Leste"),
)

val DefaultCountryCode = CountryCodes.first { it.iso == "EG" }
